# Generated by Django 4.1.3 on 2022-11-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Xkrules',
        ),
    ]
