# Generated by Django 4.1.3 on 2022-11-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_product_img1_alter_product_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
