# Generated by Django 4.1.3 on 2022-11-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductCode',
            field=models.CharField(max_length=500),
        ),
    ]
