# Generated by Django 4.1.3 on 2022-11-27 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_product_productcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Title',
        ),
    ]
