# Generated by Django 4.1.3 on 2022-12-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_remove_product_size_remove_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Img1',
            field=models.ImageField(default='', upload_to='uploads/Product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Img2',
            field=models.ImageField(default='', upload_to='uploads/Product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Img3',
            field=models.ImageField(default='', upload_to='uploads/Product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Img4',
            field=models.ImageField(default='', upload_to='uploads/Product/'),
        ),
    ]
