# Generated by Django 4.1.3 on 2022-12-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_rename_productcode_product_productname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
