# Generated by Django 4.1.3 on 2022-12-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_rename_discount_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Discount',
            field=models.CharField(default=1, max_length=3),
        ),
    ]
