# Generated by Django 4.1.3 on 2022-12-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Discount',
            field=models.DecimalField(decimal_places=1, default=0.1, max_digits=3),
        ),
    ]
