# Generated by Django 4.1.3 on 2022-11-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Img1',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
