# Generated by Django 4.1.3 on 2022-11-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_category_img1'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
    ]
