# Generated by Django 4.1.3 on 2022-11-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_alter_category_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Img1',
            field=models.ImageField(default='', upload_to='Media'),
        ),
    ]
