# Generated by Django 4.1.3 on 2022-11-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0004_alter_category_img1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Img1',
            field=models.ImageField(default='', upload_to='uploads/products/'),
        ),
    ]
