# Generated by Django 4.1.3 on 2022-11-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0005_alter_category_img1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Code',
            field=models.CharField(max_length=200),
        ),
    ]
