# Generated by Django 4.1.3 on 2022-11-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0006_alter_category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ParentId',
            field=models.BigIntegerField(default=0),
        ),
    ]
